### ISSUE TITLE
Triggering a route even if it's not in previousState

### ISSUE THREAD

**Issue by itzaks** [baseprime/grapnel#32] opened 2015-03-18 11:18 UTC
Hello!

Thanks for a great router :+1: 

I have an issue where navigating using browser history upon page load is not triggering navigate(). 

It has to do with this piece:

```
root.addEventListener('popstate', function(e){
     // Make sure popstate doesn't run on init -- this is a common issue with Safari and old versions of Chrome
    if(self.state && self.state.previousState === null) return false;

    self.trigger('navigate');
});
```

`self.state.previousState` is null on page load; thus when my browser history contains a route which is on my app domain and is listenable and I navigate to it, it wont trigger. Is there a workaround for this? Removing `if(self.state && self.state.previousState === null) return false;` solves it for me, but judging by the comment it's not a very good idea to remove it :)

**Comment by itzaks** [comment] 2015-03-18 11:21
Ah, seems like this was caused by this fix 470c124a82331b03d37e736f850e9a3f100c1bb3.

**Comment by EngineeringMode** [comment] 2015-03-25 04:22
Unless otherwise specified, there are no routes triggered when the router is initialized, only after it's initialized, therefore `self.state.previousState` must be null. In fact, the `self.state` property is null until a state is created by navigating, either from pushState or hashchange. So technically, `self.state.previousState` is undefined on initialization.

If I understand your problem correctly, you could create a workaround by firing an event once the DOM navigates. But generally, Grapnel only manages routes it creates after initialization. If you navigate (using popstate or hashChange), then those events are out of the Grapnel's scope.

**Comment by itzaks** [comment] 2015-03-25 08:41
Thanks for the response. It is not really that I wish it triggered routes before init, just that if I have in my browser history a route that will match a route in grapnel, then I can't reach it, because it has no `self.state.previousState`. But technically it could match and trigger that route, I think this is the behaviour in Backbones router for example.

Here's an example for a better explanation :)

Say we navigate to `http://localhost:3000/`, we click a link that leads to `http://localhost:3000/clients`. So far I am able to navigate back and forth by pushState and Grapnel. 

Now, if the page is refreshed on `http://localhost:3000/clients`, and I go back one step in history using the browser, the url will change to `http://localhost:3000/` but the route in Grapnel is not triggered.

**Comment by EngineeringMode** [comment] 2015-03-25 19:18
Do you have a route for `/`? Is `/clients` loading the router when the page is refreshed?

**Comment by itzaks** [comment] 2015-03-26 09:12
Yes, and yes :)

**Comment by corneldm** [comment] 2015-07-20 23:22
I just ran into this same issue, similar case for reproducing it:
1. Browse to '/'
2. navigate('/page/2')
3. Click a link to load '/foo' (pushstate not used)
4. Hit back in browser to load '/page/2' from cache
6. Hit back again — navigate is not called since previousState === null

If I can manage to reproduce the Safari issue, I'll submit a PR; otherwise, I'll just fork and remove that short-circuit conditional.

Aside from this, Grapnel has been fantastic! Thanks for your work, @EngineeringMode

**Comment by seogrady** [comment] 2016-09-25 13:44
Hello! Did anything come of this issue? Just been testing out the router and everything works great except this issue.  Happy to work on a fix if anyone can give some insight.  Thanks

**Comment by baseprime** [comment] 2016-09-27 00:55
This will be fixed in an upcoming release that will allow history/pushState traversal. 😄  @seogrady @corneldm @itzaks

**Comment by itzaks** [comment] 2016-10-11 13:03
cool, thanks!

**Comment by rdy** [comment] 2016-10-24 19:25
Just curious what the ETA for the new release was, I'm looking for the same fix on grapnel as well. 

Thanks for all the great work!

**Closed** 2018-10-02 23:08 UTC
Labels: bug
